### ISSUE TITLE
Setup tests

### ISSUE THREAD

**Issue by mir4a** [mir4a/shrt#7]
[Meteor testing guide](https://guide.meteor.com/testing.html)

**Comment by mir4a** [comment]
```
.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: You must specify a driver package with --driver-package
    at doTestCommand (/tools/cli/commands.js:1626:13)
    at Command.func (/tools/cli/commands.js:1498:10)
    at /tools/cli/main.js:1410:23
```
